[2023-12-06 08:00:05,585] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: meeting.merge_data 2023-12-06T07:00:00+00:00 [queued]>
[2023-12-06 08:00:05,594] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: meeting.merge_data 2023-12-06T07:00:00+00:00 [queued]>
[2023-12-06 08:00:05,595] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2023-12-06 08:00:05,595] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2023-12-06 08:00:05,595] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2023-12-06 08:00:05,606] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): merge_data> on 2023-12-06T07:00:00+00:00
[2023-12-06 08:00:05,610] {standard_task_runner.py:52} INFO - Started process 6023 to run task
[2023-12-06 08:00:05,613] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'meeting', 'merge_data', '2023-12-06T07:00:00+00:00', '--job-id', '96', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp6uqninm5', '--error-file', '/tmp/tmpsi4zmp25']
[2023-12-06 08:00:05,616] {standard_task_runner.py:77} INFO - Job 96: Subtask merge_data
[2023-12-06 08:00:05,654] {logging_mixin.py:109} INFO - Running <TaskInstance: meeting.merge_data 2023-12-06T07:00:00+00:00 [running]> on host 290bde24ac9b
[2023-12-06 08:00:05,704] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=meeting
AIRFLOW_CTX_TASK_ID=merge_data
AIRFLOW_CTX_EXECUTION_DATE=2023-12-06T07:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-12-06T07:00:00+00:00
[2023-12-06 08:00:05,727] {python.py:151} INFO - Done. Returned value was: None
[2023-12-06 08:00:05,737] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=meeting, task_id=merge_data, execution_date=20231206T070000, start_date=20231206T080005, end_date=20231206T080005
[2023-12-06 08:00:05,785] {local_task_job.py:151} INFO - Task exited with return code 0
[2023-12-06 08:00:05,805] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
