[2024-01-28 07:55:13,728] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: meeting.merge_data 2024-01-28T07:55:07.924342+00:00 [queued]>
[2024-01-28 07:55:13,743] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: meeting.merge_data 2024-01-28T07:55:07.924342+00:00 [queued]>
[2024-01-28 07:55:13,743] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2024-01-28 07:55:13,743] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2024-01-28 07:55:13,743] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2024-01-28 07:55:13,751] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): merge_data> on 2024-01-28T07:55:07.924342+00:00
[2024-01-28 07:55:13,756] {standard_task_runner.py:52} INFO - Started process 1876 to run task
[2024-01-28 07:55:13,758] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'meeting', 'merge_data', '2024-01-28T07:55:07.924342+00:00', '--job-id', '157', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp8efzx_8c', '--error-file', '/tmp/tmpm0ja8qtt']
[2024-01-28 07:55:13,761] {standard_task_runner.py:77} INFO - Job 157: Subtask merge_data
[2024-01-28 07:55:13,794] {logging_mixin.py:109} INFO - Running <TaskInstance: meeting.merge_data 2024-01-28T07:55:07.924342+00:00 [running]> on host b3b11241a43d
[2024-01-28 07:55:13,841] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=meeting
AIRFLOW_CTX_TASK_ID=merge_data
AIRFLOW_CTX_EXECUTION_DATE=2024-01-28T07:55:07.924342+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-28T07:55:07.924342+00:00
[2024-01-28 07:55:13,862] {python.py:151} INFO - Done. Returned value was: None
[2024-01-28 07:55:13,873] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=meeting, task_id=merge_data, execution_date=20240128T075507, start_date=20240128T075513, end_date=20240128T075513
[2024-01-28 07:55:13,891] {local_task_job.py:151} INFO - Task exited with return code 0
[2024-01-28 07:55:13,913] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
